version: '3.9'

services:
  frontend:
    build: 
      context: .
      dockerfile: frontend.Dockerfile
    container_name: inno-alumni-frontend
    ports:
      - 3000:3000
    volumes:
      - ./:/usr/src/app
    command: npm run next-dev
    depends_on:
      - backend

  backend: 
    build: 
      context: .
      dockerfile: backend.Dockerfile
    container_name: inno-alumni-backend
    env_file:
      - ./.env
    ports:
      - 9000:8000
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./:/usr/src/app

  # nginx:
  #   image: nginx:1.22-alpine
  #   restart: always
  #   container_name: nginx
  #   volumes:
  #     - ./data/nginx:/etc/nginx/conf.d
  #     - ./data/certbot/conf:/etc/letsencrypt
  #     - ./data/certbot/www:/var/www/certbot
  #   ports:
  #     - 80:80
  #     - 443:443
  #   command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  # certbot:
  #   image: certbot/certbot
  #   restart: always
  #   container_name: certbot
  #   volumes:
  #     - ./data/certbot/conf:/etc/letsencrypt
  #     - ./data/certbot/www:/var/www/certbot
  #   entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
