version: '3.9'


services:
# TODO add database browser in the browser if possible
  # sqlite3:
  #   container_name: sqlite3_container
  #   image: nouchka/sqlite3:latest
  #   stdin_open: true
  #   tty: true
  #   volumes:
  #     - ./Backend:/root/db/
  #   ports:
  #     - '9000:9000' # expose ports - HOST:CONTAINER
  #   restart: unless-stopped

  # Todo make db image when needed
  # db:
  #   image: postgres:14-alpine
  #   ports:
  #     - '5432:5432'

  #   environment:
  #     - POSTGRES_PASSWORD=postgres
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_DB=postgres

  #   volumes:
  #     - ./data/db:/var/lib/postgresql/data/

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile

    ports:
      - '3000:3000'

    volumes:
      - ./frontend:/app/frontend

    depends_on:
      - backend

  backend: 
    build: 
      context: ./Backend
      dockerfile: Dockerfile

    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres

    ports:
      - '8000:8000'

    volumes:
      - ./backend:/app/backend
    # TODO add with database server
    # depends_on:
    #   - db

  nginx:
    container_name: nginx
    image: nginx
    volumes:
      - ./Nginx/conf.d:/etc/nginx/conf.d:ro
      - ./frontend:/app/frontend
    ports:
      - 80:80
    restart: unless-stopped
    depends_on:
      - backend
      - frontend

